from .i_vertex_manager import VertexManagerInterface
from .i_edge_manager import EdgeManagerInterface
from .i_color_manager import ColorManagerInterface
from .i_polygon_manager import PolygonManagerInterface
from .i_translation_manager import TranslationManagerInterface
from .i_theme_manager import ThemeManagerInterface